// export const defaultConfig = {
//   name: "John Doe",
//   title: "Full Stack Developer",
//   location: "Remote",
//   email: "example@mail.com",
//   phone: "+1234567890",
//   linkedin: "https://linkedin.com",
//   github: "https://github.com",
//   summary_heading: "Professional Summary",
//   skills_heading: "Skills",
//   experience_heading: "Experience",
//   education_heading: "Education",
//   projects_heading: "Projects",
//   cta_button: "Contact Me",
//   background_color: "#0F1117",
//   card_color: "#1E293B",
//   text_color: "#FFFFFF",
//   primary_color: "#3B82F6",
//   accent_color: "#10B981",
//   font_family: "Inter",
//   font_size: 16
// };

export const defaultConfig = {
background_color: '#0a0a0a',
card_color: '#141414',
primary_color: '#00ff88',
text_color: '#ffffff',
accent_color: '#00d9ff',
font_family: 'Inter, ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto',
font_size: 16,
name: 'SULEIMAN MOHAMMED GARBA',
title: 'Full Stack JavaScript Software Engineer',
location: 'Minna, Nigeria',
email: 'suleimang34@gmail.com',
phone: '+2348036020110',
linkedin: 'suleimangarba',
github: 'nasiest',
summary_heading: 'Professional Summary',
skills_heading: 'Core Skills',
experience_heading: 'Professional Experience',
education_heading: 'Education & Certifications',
projects_heading: 'Project Highlights',
cta_button: 'Get In Touch'
};